// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi1wdILMJC17ZUTdCD6wW_8aRt5hKkBs8',
    appId: '1:861363392391:ios:0b09b269741784a906cd22',
    messagingSenderId: '861363392391',
    projectId: 'mychat-b5d06',
    databaseURL: 'https://mychat-b5d06-default-rtdb.firebaseio.com',
    storageBucket: 'mychat-b5d06.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tSQdRPmP62CEHiXFrvykNn5Qp7wf140',
    appId: '1:861363392391:web:6f1b6424f912aed906cd22',
    messagingSenderId: '861363392391',
    projectId: 'mychat-b5d06',
    authDomain: 'mychat-b5d06.firebaseapp.com',
    databaseURL: 'https://mychat-b5d06-default-rtdb.firebaseio.com',
    storageBucket: 'mychat-b5d06.firebasestorage.app',
    measurementId: 'G-HR1R98ZXM2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tSQdRPmP62CEHiXFrvykNn5Qp7wf140',
    appId: '1:861363392391:web:6f1b6424f912aed906cd22',
    messagingSenderId: '861363392391',
    projectId: 'mychat-b5d06',
    authDomain: 'mychat-b5d06.firebaseapp.com',
    databaseURL: 'https://mychat-b5d06-default-rtdb.firebaseio.com',
    storageBucket: 'mychat-b5d06.firebasestorage.app',
    measurementId: 'G-HR1R98ZXM2',
  );

}